### ISSUE TITLE
WCMS-3056-3: Make a list of guides

### ISSUE THREAD

**Issue by mthpvg** [upfrontIO/livingdocs#38]
Internal discussion on what guides we need.
Conduct some interviews of people from the Livingdocs team and the teams at NZZ:
- Present the taxonomy
- Present the table of contents of the central documentation (livingdocs repository)
- Regarding what was presented, ask : "what documentation have you been missing ?"

### Deliverables
A document holding the list of guides

**Comment by masone** [comment]
This task has potential to get out of hand. I would go for simple / concrete questions instead of having an open discussion based on the documents you prepared. It will take a lot of time for everyone to get into the right mindset and to assess all of your suggestions. We can do that internally for the ones that want to have a say. But for just having a list of guides, I'd go for just asking everyone questions like "what documentation have you been missing"?

**Comment by masone** [comment]
moved to https://github.com/upfrontIO/livingdocs-planning/issues/13
